// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfvwqmxasgptaeocmgwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmdndxbXhhc2dwdGFlb2NtZ3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzcyNjMsImV4cCI6MjA2Nzc1MzI2M30.BmWx-Tc8gNbjTOrmJqvEBQbnJE2pwXqgN-UsPUGhPk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});